/**
 * generated by Xtext 2.23.0
 */
package jasonide.xtext.asl.asl;

import java.lang.String;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Plan</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link jasonide.xtext.asl.asl.Plan#getTk_label_at <em>Tk label at</em>}</li>
 *   <li>{@link jasonide.xtext.asl.asl.Plan#getLiteral <em>Literal</em>}</li>
 *   <li>{@link jasonide.xtext.asl.asl.Plan#getList <em>List</em>}</li>
 *   <li>{@link jasonide.xtext.asl.asl.Plan#getTrigger <em>Trigger</em>}</li>
 *   <li>{@link jasonide.xtext.asl.asl.Plan#getLog_expr <em>Log expr</em>}</li>
 *   <li>{@link jasonide.xtext.asl.asl.Plan#getPlan_body <em>Plan body</em>}</li>
 * </ul>
 *
 * @see jasonide.xtext.asl.asl.AslPackage#getPlan()
 * @model
 * @generated
 */
public interface Plan extends EObject
{
  /**
   * Returns the value of the '<em><b>Tk label at</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tk label at</em>' attribute.
   * @see #setTk_label_at(String)
   * @see jasonide.xtext.asl.asl.AslPackage#getPlan_Tk_label_at()
   * @model
   * @generated
   */
  String getTk_label_at();

  /**
   * Sets the value of the '{@link jasonide.xtext.asl.asl.Plan#getTk_label_at <em>Tk label at</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tk label at</em>' attribute.
   * @see #getTk_label_at()
   * @generated
   */
  void setTk_label_at(String value);

  /**
   * Returns the value of the '<em><b>Literal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Literal</em>' containment reference.
   * @see #setLiteral(Literal)
   * @see jasonide.xtext.asl.asl.AslPackage#getPlan_Literal()
   * @model containment="true"
   * @generated
   */
  Literal getLiteral();

  /**
   * Sets the value of the '{@link jasonide.xtext.asl.asl.Plan#getLiteral <em>Literal</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Literal</em>' containment reference.
   * @see #getLiteral()
   * @generated
   */
  void setLiteral(Literal value);

  /**
   * Returns the value of the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' containment reference.
   * @see #setList(List)
   * @see jasonide.xtext.asl.asl.AslPackage#getPlan_List()
   * @model containment="true"
   * @generated
   */
  List getList();

  /**
   * Sets the value of the '{@link jasonide.xtext.asl.asl.Plan#getList <em>List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List</em>' containment reference.
   * @see #getList()
   * @generated
   */
  void setList(List value);

  /**
   * Returns the value of the '<em><b>Trigger</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trigger</em>' containment reference.
   * @see #setTrigger(Trigger)
   * @see jasonide.xtext.asl.asl.AslPackage#getPlan_Trigger()
   * @model containment="true"
   * @generated
   */
  Trigger getTrigger();

  /**
   * Sets the value of the '{@link jasonide.xtext.asl.asl.Plan#getTrigger <em>Trigger</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Trigger</em>' containment reference.
   * @see #getTrigger()
   * @generated
   */
  void setTrigger(Trigger value);

  /**
   * Returns the value of the '<em><b>Log expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Log expr</em>' containment reference.
   * @see #setLog_expr(Log_expr)
   * @see jasonide.xtext.asl.asl.AslPackage#getPlan_Log_expr()
   * @model containment="true"
   * @generated
   */
  Log_expr getLog_expr();

  /**
   * Sets the value of the '{@link jasonide.xtext.asl.asl.Plan#getLog_expr <em>Log expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Log expr</em>' containment reference.
   * @see #getLog_expr()
   * @generated
   */
  void setLog_expr(Log_expr value);

  /**
   * Returns the value of the '<em><b>Plan body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plan body</em>' containment reference.
   * @see #setPlan_body(Plan_body)
   * @see jasonide.xtext.asl.asl.AslPackage#getPlan_Plan_body()
   * @model containment="true"
   * @generated
   */
  Plan_body getPlan_body();

  /**
   * Sets the value of the '{@link jasonide.xtext.asl.asl.Plan#getPlan_body <em>Plan body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plan body</em>' containment reference.
   * @see #getPlan_body()
   * @generated
   */
  void setPlan_body(Plan_body value);

} // Plan
