/**
 * generated by Xtext 2.23.0
 */
package jasonide.xtext.asl.asl;

import java.lang.String;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stmt IF Common</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link jasonide.xtext.asl.asl.StmtIFCommon#getLog_expr <em>Log expr</em>}</li>
 *   <li>{@link jasonide.xtext.asl.asl.StmtIFCommon#getPlan_term <em>Plan term</em>}</li>
 *   <li>{@link jasonide.xtext.asl.asl.StmtIFCommon#getTk_elif <em>Tk elif</em>}</li>
 *   <li>{@link jasonide.xtext.asl.asl.StmtIFCommon#getStmtIFCommon <em>Stmt IF Common</em>}</li>
 *   <li>{@link jasonide.xtext.asl.asl.StmtIFCommon#getTk_else <em>Tk else</em>}</li>
 *   <li>{@link jasonide.xtext.asl.asl.StmtIFCommon#getPlan_term2 <em>Plan term2</em>}</li>
 * </ul>
 *
 * @see jasonide.xtext.asl.asl.AslPackage#getStmtIFCommon()
 * @model
 * @generated
 */
public interface StmtIFCommon extends EObject
{
  /**
   * Returns the value of the '<em><b>Log expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Log expr</em>' containment reference.
   * @see #setLog_expr(Log_expr)
   * @see jasonide.xtext.asl.asl.AslPackage#getStmtIFCommon_Log_expr()
   * @model containment="true"
   * @generated
   */
  Log_expr getLog_expr();

  /**
   * Sets the value of the '{@link jasonide.xtext.asl.asl.StmtIFCommon#getLog_expr <em>Log expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Log expr</em>' containment reference.
   * @see #getLog_expr()
   * @generated
   */
  void setLog_expr(Log_expr value);

  /**
   * Returns the value of the '<em><b>Plan term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plan term</em>' containment reference.
   * @see #setPlan_term(Plan_term)
   * @see jasonide.xtext.asl.asl.AslPackage#getStmtIFCommon_Plan_term()
   * @model containment="true"
   * @generated
   */
  Plan_term getPlan_term();

  /**
   * Sets the value of the '{@link jasonide.xtext.asl.asl.StmtIFCommon#getPlan_term <em>Plan term</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plan term</em>' containment reference.
   * @see #getPlan_term()
   * @generated
   */
  void setPlan_term(Plan_term value);

  /**
   * Returns the value of the '<em><b>Tk elif</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tk elif</em>' attribute.
   * @see #setTk_elif(String)
   * @see jasonide.xtext.asl.asl.AslPackage#getStmtIFCommon_Tk_elif()
   * @model
   * @generated
   */
  String getTk_elif();

  /**
   * Sets the value of the '{@link jasonide.xtext.asl.asl.StmtIFCommon#getTk_elif <em>Tk elif</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tk elif</em>' attribute.
   * @see #getTk_elif()
   * @generated
   */
  void setTk_elif(String value);

  /**
   * Returns the value of the '<em><b>Stmt IF Common</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stmt IF Common</em>' containment reference.
   * @see #setStmtIFCommon(StmtIFCommon)
   * @see jasonide.xtext.asl.asl.AslPackage#getStmtIFCommon_StmtIFCommon()
   * @model containment="true"
   * @generated
   */
  StmtIFCommon getStmtIFCommon();

  /**
   * Sets the value of the '{@link jasonide.xtext.asl.asl.StmtIFCommon#getStmtIFCommon <em>Stmt IF Common</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stmt IF Common</em>' containment reference.
   * @see #getStmtIFCommon()
   * @generated
   */
  void setStmtIFCommon(StmtIFCommon value);

  /**
   * Returns the value of the '<em><b>Tk else</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tk else</em>' attribute.
   * @see #setTk_else(String)
   * @see jasonide.xtext.asl.asl.AslPackage#getStmtIFCommon_Tk_else()
   * @model
   * @generated
   */
  String getTk_else();

  /**
   * Sets the value of the '{@link jasonide.xtext.asl.asl.StmtIFCommon#getTk_else <em>Tk else</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tk else</em>' attribute.
   * @see #getTk_else()
   * @generated
   */
  void setTk_else(String value);

  /**
   * Returns the value of the '<em><b>Plan term2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plan term2</em>' containment reference.
   * @see #setPlan_term2(Plan_term)
   * @see jasonide.xtext.asl.asl.AslPackage#getStmtIFCommon_Plan_term2()
   * @model containment="true"
   * @generated
   */
  Plan_term getPlan_term2();

  /**
   * Sets the value of the '{@link jasonide.xtext.asl.asl.StmtIFCommon#getPlan_term2 <em>Plan term2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plan term2</em>' containment reference.
   * @see #getPlan_term2()
   * @generated
   */
  void setPlan_term2(Plan_term value);

} // StmtIFCommon
