/**
 * generated by Xtext 2.23.0
 */
package jasonide.xtext.asl.asl;

import java.lang.String;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stmt IF</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link jasonide.xtext.asl.asl.StmtIF#getTk_if <em>Tk if</em>}</li>
 *   <li>{@link jasonide.xtext.asl.asl.StmtIF#getStmtIFCommon <em>Stmt IF Common</em>}</li>
 * </ul>
 *
 * @see jasonide.xtext.asl.asl.AslPackage#getStmtIF()
 * @model
 * @generated
 */
public interface StmtIF extends EObject
{
  /**
   * Returns the value of the '<em><b>Tk if</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tk if</em>' attribute.
   * @see #setTk_if(String)
   * @see jasonide.xtext.asl.asl.AslPackage#getStmtIF_Tk_if()
   * @model
   * @generated
   */
  String getTk_if();

  /**
   * Sets the value of the '{@link jasonide.xtext.asl.asl.StmtIF#getTk_if <em>Tk if</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tk if</em>' attribute.
   * @see #getTk_if()
   * @generated
   */
  void setTk_if(String value);

  /**
   * Returns the value of the '<em><b>Stmt IF Common</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stmt IF Common</em>' containment reference.
   * @see #setStmtIFCommon(StmtIFCommon)
   * @see jasonide.xtext.asl.asl.AslPackage#getStmtIF_StmtIFCommon()
   * @model containment="true"
   * @generated
   */
  StmtIFCommon getStmtIFCommon();

  /**
   * Sets the value of the '{@link jasonide.xtext.asl.asl.StmtIF#getStmtIFCommon <em>Stmt IF Common</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stmt IF Common</em>' containment reference.
   * @see #getStmtIFCommon()
   * @generated
   */
  void setStmtIFCommon(StmtIFCommon value);

} // StmtIF
