/**
 * generated by Xtext 2.23.0
 */
package jasonide.xtext.asl.asl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Terms</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link jasonide.xtext.asl.asl.Terms#getTerm <em>Term</em>}</li>
 * </ul>
 *
 * @see jasonide.xtext.asl.asl.AslPackage#getTerms()
 * @model
 * @generated
 */
public interface Terms extends EObject
{
  /**
   * Returns the value of the '<em><b>Term</b></em>' containment reference list.
   * The list contents are of type {@link jasonide.xtext.asl.asl.Term}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Term</em>' containment reference list.
   * @see jasonide.xtext.asl.asl.AslPackage#getTerms_Term()
   * @model containment="true"
   * @generated
   */
  EList<Term> getTerm();

} // Terms
