/*
 * generated by Xtext
 */
package jasonide.xtext.mas2j.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import jasonide.xtext.mas2j.ui.internal.Mas2jActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Mas2jExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Mas2jActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Mas2jActivator.getInstance().getInjector(Mas2jActivator.JASONIDE_XTEXT_MAS2J_MAS2J);
	}
	
}
