/*
 * generated by Xtext 2.23.0
 */
package jasonide.xtext.mas2j.ui;

import com.google.inject.Injector;
import jasonide.xtext.mas2j.ui.internal.Mas2jActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Mas2jExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Mas2jActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		Mas2jActivator activator = Mas2jActivator.getInstance();
		return activator != null ? activator.getInjector(Mas2jActivator.JASONIDE_XTEXT_MAS2J_MAS2J) : null;
	}

}
