/*
 * generated by Xtext 2.23.0
 */
package jasonide.xtext.mas2j.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import jasonide.xtext.mas2j.Mas2jRuntimeModule;
import jasonide.xtext.mas2j.Mas2jStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class Mas2jIdeSetup extends Mas2jStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new Mas2jRuntimeModule(), new Mas2jIdeModule()));
	}
	
}
