/*
 * generated by Xtext 2.23.0
 */
package jasonide.xtext.asl.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class AslScopeProvider extends AbstractAslScopeProvider {

}
