/*
 * generated by Xtext 2.23.0
 */
package jasonide.xtext.mas2j.ui.tests;

import com.google.inject.Injector;
import jasonide.xtext.mas2j.ui.internal.Mas2jActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class Mas2jUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Mas2jActivator.getInstance().getInjector("jasonide.xtext.mas2j.Mas2j");
	}

}
