/*
 * generated by Xtext 2.23.0
 */
package jasonide.xtext.asl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.outline.IOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;

import jasonide.xtext.asl.ui.outline.AslOutlineTreeProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AslUiModule extends AbstractAslUiModule {

	public AslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration () {
	    return AslHighlightingConfiguration.class;
	}
	
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator(){
		return AslHighlightingCalculator.class;
	}
	
	public Class<? extends IOutlineTreeProvider> bindIOutlineTreeProvider() {
	    return AslOutlineTreeProvider.class;
	}
}
