/*
 * generated by Xtext 2.23.0
 */
package jasonide.xtext.mas2j.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMas2jValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(jasonide.xtext.mas2j.mas2j.Mas2jPackage.eINSTANCE);
		return result;
	}
}
