/**
 * generated by Xtext 2.23.0
 */
package jasonide.xtext.mas2j.mas2j;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mindinspector</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link jasonide.xtext.mas2j.mas2j.Mindinspector#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see jasonide.xtext.mas2j.mas2j.Mas2jPackage#getMindinspector()
 * @model
 * @generated
 */
public interface Mindinspector extends Option
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(String)
   * @see jasonide.xtext.mas2j.mas2j.Mas2jPackage#getMindinspector_Val()
   * @model
   * @generated
   */
  String getVal();

  /**
   * Sets the value of the '{@link jasonide.xtext.mas2j.mas2j.Mindinspector#getVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #getVal()
   * @generated
   */
  void setVal(String value);

} // Mindinspector
