/**
 * generated by Xtext 2.23.0
 */
package jasonide.xtext.mas2j.mas2j;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Requeue Events</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see jasonide.xtext.mas2j.mas2j.Mas2jPackage#getRequeueEvents()
 * @model
 * @generated
 */
public interface RequeueEvents extends Events
{
} // RequeueEvents
