/*
 * generated by Xtext 2.23.0
 */
package jasonide.xtext.asl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import jasonide.xtext.asl.AslRuntimeModule;
import jasonide.xtext.asl.AslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AslIdeSetup extends AslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AslRuntimeModule(), new AslIdeModule()));
	}
	
}
