/*
 * generated by Xtext 2.23.0
 */
package jasonide.xtext.mas2j.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMas2jScopeProvider extends DelegatingScopeProvider {
}
