/*
 * generated by Xtext 2.23.0
 */
package jasonide.xtext.mas2j;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Mas2jRuntimeModule extends AbstractMas2jRuntimeModule {
}
