/*
 * generated by Xtext
 */
package jasonide.xtext.asl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import jasonide.xtext.asl.ui.internal.AslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AslActivator.getInstance().getInjector(AslActivator.JASONIDE_XTEXT_ASL_ASL);
	}
	
}
