/*
 * generated by Xtext 2.23.0
 */
package jasonide.xtext.mas2j.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.outline.IOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;

import jasonide.xtext.mas2j.ui.outline.Mas2jOutlineTreeProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Mas2jUiModule extends AbstractMas2jUiModule {

	public Mas2jUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration () {
	    return Mas2jHighlightingConfiguration.class;
	}
	
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator(){
		return Mas2jHighlightingCalculator.class;
	}
	
	public Class<? extends IOutlineTreeProvider> bindIOutlineTreeProvider() {
	    return Mas2jOutlineTreeProvider.class;
	}
	
}
