/*
 * generated by Xtext 2.23.0
 */
package jasonide.xtext.asl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAslScopeProvider extends DelegatingScopeProvider {
}
